name: Mula-Api

on:
  push:
    branches: [ master ]
jobs:
  laravel-deployer:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.MULA_API_TEST_HOST }}
          username: ${{ secrets.MULA_API_TEST_USERNAME }}
          password: ${{ secrets.MULA_API_TEST_PASS }}
          script: 'cd /var/www/html/api/mula-api-test && ./deployer.sh'
